version: '3.7'

services:
  vault:
    image: letfn/vault
    volumes:
      - ./etc/vault:/config
    cap_add:
      - IPC_LOCK
    labels:
      - "app=vault"
      - "zone=kitt"
      - "traefik.enable=true"
      - "traefik.http.routers.vault.tls=true"
      - "traefik.http.routers.vault.entrypoints=https"
      - "traefik.http.routers.vault.rule=HostRegexp(`vault.{domain:.+}`)"
      - "traefik.http.services.vault.loadbalancer.server.port=8200"
    networks:
      default:
        ipv4_address: ${KITT_NETWORK_PREFIX}.54

networks:
  default:
    external:
      name: kitt_default
