version: '3.7'

services:
  vault:
    image: defn/vault:1.6.3
    volumes:
      - ./etc/vault:/config
    cap_add:
      - IPC_LOCK
    labels:
      - "SERVICE_NAME=vault"
      - "SERVICE_TAGS=traefik.enable=true,traefik.http.routers.vault.entrypoints=https,traefik.http.routers.vault.rule=HostRegexp(`vault.{domain:.+}`),traefik.http.services.vault.loadbalancer.server.port=8200"
      - "app=vault"
      - "zone=kitt"
    ports:
      - 8200
    env_file: ./.env
    networks:
      default:
        ipv4_address: ${KITT_NETWORK_PREFIX}.54
    restart: always

networks:
  default:
    external:
      name: kitt_default
